# This is a basic workflow to help you get started with Actions
name: Deploy to live

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the main "main" branch, this will also work for merging pull requests into "main"
  push:
    branches: [ "main" ]
  # Ignores all branches for pull requests
  pull_request:
    branches-ignore: [ "**" ]
  # Ignores all branches for pull request target
  pull_request_target:
    branches-ignore: [ "**" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ftp-deploy"
  ftp-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout latest changes
        uses: actions/checkout@v3


      # Deploy files to server via FTP
      - name: Deploy changes via ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.simplifybiz.com
          username: ${{ secrets.FTP_LIVE_USERNAME }}
          password: ${{ secrets.FTP_LIVE_PASSWORD }}
          server-dir: /wp-content/plugins/smplfy-appsimplifybiz/
          exclude: |
            **/exclude/**
            **/.github/**   
